---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.1
  kernelspec:
    display_name: R
    language: R
    name: ir
---

Test de classification avec la méthode des Forêts aléatoires et
[ranger](https://github.com/imbs-hl/ranger).

L'exemple provient de
[A minimal benchmark for scalability, speed and accuracy of commonly used open source implementations (R packages, Python scikit-learn, H2O, xgboost, Spark MLlib etc.) of the top machine learning algorithms for binary classification (random forests, gradient boosted trees, deep neural networks etc.).](https://github.com/szilard/benchm-ml)

```{r}
library(readr)
library(ranger)
library(ROCR)

d_train <- read_csv("https://s3.amazonaws.com/benchm-ml--main/train-0.1m.csv")
d_test <- read_csv("https://s3.amazonaws.com/benchm-ml--main/test.csv")

d_train$dep_delayed_15min <- as.factor(d_train$dep_delayed_15min)
d_test$dep_delayed_15min  <- as.factor(d_test$dep_delayed_15min)
```

```{r}
system.time({
  md <- ranger(dep_delayed_15min ~ ., d_train, num.trees = 100, probability = TRUE, write.forest = TRUE)
})
```

```{r}
system.time({
  phat <- predictions(predict(md, data = d_test))[,"Y"]
})
```

```{r}
rocr_pred <- prediction(phat, d_test$dep_delayed_15min)
performance(rocr_pred, "auc")
```
